---
title: df_san Profiling Report
dataset:
  description: ''
  creator: ''
  author: ''
  copyright_holder: ''
  copyright_year: ''
  url: ''
variables:
  descriptions: {}
infer_dtypes: false
show_variable_description: true
pool_size: 0
progress_bar: true
vars:
  num:
    quantiles:
    - 0.05
    - 0.25
    - 0.5
    - 0.75
    - 0.95
    skewness_threshold: 20
    low_categorical_threshold: 5
    chi_squared_threshold: 0
  cat:
    length: false
    characters: false
    words: false
    cardinality_threshold: 50
    n_obs: 5
    chi_squared_threshold: 0
    coerce_str_to_date: false
    redact: false
    histogram_largest: 10
  image:
    active: false
    exif: false
    hash: false
  bool:
    n_obs: 3
    mappings:
      t: true
      f: false
      'True': true
      'False': false
      y: true
      n: false
  path:
    active: false
  file:
    active: false
  url:
    active: false
sort:
missing_diagrams:
  bar: false
  matrix: false
  heatmap: false
  dendrogram: false
correlations:
  pearson:
    key: ''
    calculate: true
    warn_high_correlations: 1
    threshold: 0.9
  spearman:
    key: ''
    calculate: false
    warn_high_correlations: 0
    threshold: 0.9
  kendall:
    key: ''
    calculate: false
    warn_high_correlations: 0
    threshold: 0.9
  phi_k:
    key: ''
    calculate: false
    warn_high_correlations: 0
    threshold: 0.9
  cramers:
    key: ''
    calculate: false
    warn_high_correlations: 1
    threshold: 0.9
interactions:
  continuous: false
  targets: []
categorical_maximum_correlation_distinct: 100
memory_deep: false
plot:
  missing:
    force_labels: true
    cmap: RdBu
  image_format: svg
  correlation:
    cmap: RdBu
    bad: "#000000"
  dpi: 800
  histogram:
    bins: 50
    max_bins: 250
    x_axis_labels: true
  scatter_threshold: 1000
  pie:
    max_unique: 0
duplicates:
  head: 4
  key: "# duplicates"
samples:
  head: 0
  tail: 0
  random: 0
reject_variables: true
n_obs_unique: 5
n_freq_table_max: 10
n_extreme_obs: 5
report:
  precision: 10
html:
  style:
    primary_color: "#337ab7"
    logo: ''
    theme:
  navbar_show: true
  minify_html: false
  use_local_assets: true
  inline: true
  assets_prefix:
  assets_path:
  full_width: false
notebook:
  iframe:
    height: 800px
    width: 100%
    attribute: srcdoc
